### PR TITLE
Checklist for externally analysed (annData) datasets

### PR DESCRIPTION
**Pull request by pinin4fjords**

### CODE REVIEW

**Review by pcm32 — COMMENTED** [review]
I think that this looks good for our internal understanding. I would suggest that we add as well a separate markdown document with the explicit questions that the external submitter needs to answer, like:

- What software (and its version) was used to align reads to the reference genome?
- What is the source (please provide URL) and version of the reference genome used for alignments?
- On which AnnData slot in your object do we find the main expression matrix?
- Which units is that matrix on?

...etc.

If this is not the place for that, then of course it shouldn't avoid this PR from being merged. But if the intent of this PR is to satisfy that questionnaire, then this is what I would be after. Otherwise the submitter would need to decide what to answer based on their understanding of this checklist.

**Comment by pinin4fjords** [comment]
Is this the place for that questionnaire @anjaf ?

**Comment by anjaf** [comment]
Perhaps because I'm not too involved in this yet, I'm not quite sure. I thought this is already the description/questionnaire. If I'm seeing this right, adding the specific questions and examples makes sense. Can't the document have all: a short general description of what this is about, the list of mandatory categories and their definitions, and explicit questions to data providers if required?

**Comment by pinin4fjords** [comment]
> I think that this looks good for our internal understanding. I would suggest that we add as well a separate markdown document with the explicit questions that the external submitter needs to answer, like:

@pablo I've replicated the info in question form at the bottom per Anja's suggestion (though I do think it was pretty close to that form anyway. 

> 
> * What software (and its version) was used to align reads to the reference genome?
> * What is the source (please provide URL) and version of the reference genome used for alignments?

That might create difficulties. These matrices will often come from CellRanger, which has referencing in-built. Submitters should have access to versions, but possibly not reference files and associated URIs.

> * On which AnnData slot in your object do we find the main expression matrix?

I think the concept of 'main' might be tricky here, we just need to know how each one has been treated, and there are questions for that here. 

> * Which units is that matrix on?

Understanding treatments should get us to the answer of this.

> 
> ...etc.
> 
> If this is not the place for that, then of course it shouldn't avoid this PR from being merged. But if the intent of this PR is to satisfy that questionnaire, then this is what I would be after. Otherwise the submitter would need to decide what to answer based on their understanding of this checklist.

**Review by YalanBi — APPROVED** [review]
Thanks to all! Looks good to me. The questionnaire is clear about what information and matrix we need to process an anndata and load it to SCEA.

**Comment by pmb59** [comment]
Thanks for reviewing @YalanBi 

I have fixed a typo, and I am going to merge now this PR as it has been open for a while.

**Pull request merged**
